
[player_settings]
player_speed = 5.0
fire_interval = 0.1
player_collision_radius = 0.35
player_model_scale = 0.0044
player_model_gun_height = 110.0
player_model_gun_muzzle_offset = 100.0
anim_transition_time = 0.2

[enemy_settings]
monster_speed = 0.6
enemy_spawn_interval = 1.0
spawns_per_interval = 1
spawn_radius = 10.0

[enemy_settings.enemy_collider]
height = 0.4
radius = 0.08

[bullet_settings]
spread_amount = 20
bullet_scale = 0.3
bullet_lifetime = 1.0
bullet_speed = 15.0
rotation_per_bullet = 3.0
burn_mark_time = 5.0

[lighting_settings]
light_factor = 0.8
non_blue = 0.9
blur_scale = 2
floor_light_factor = 0.35
floor_non_blue = 0.7

[lighting_settings.light_direction]
x = -0.8
y = 0.0
z = -1.0

[lighting_settings.player_light_direction]
x = -1.0
y = -1.0
z = -1.0

[lighting_settings.muzzle_point_light_color]
x = 1.0
y = 0.2
z = 0.0

